# Generated by Django 4.2.7 on 2023-11-22 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_alter_filesmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 9, 46, 14, 327563)),
        ),
    ]
