# Generated by Django 3.2 on 2023-12-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_alter_taskmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
